-- SimpleChat Version 1 database
-- Run this entire script in Supabase SQL Editor.
--
-- Authentication:
--   - Email + password
--   - Username + password (username is resolved to the account email)
--
-- IMPORTANT:
--   Enable Email provider in Supabase Authentication > Providers.
--   For easiest development, you can disable "Confirm email".
--   For a public app, keep email confirmation enabled and configure SMTP later.

create extension if not exists pgcrypto;

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  username text not null unique,
  display_name text not null,
  created_at timestamptz not null default now()
);

create table if not exists public.conversations (
  id uuid primary key default gen_random_uuid(),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.conversation_members (
  conversation_id uuid not null references public.conversations(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  joined_at timestamptz not null default now(),
  primary key (conversation_id, user_id)
);

create table if not exists public.messages (
  id bigint generated by default as identity primary key,
  conversation_id uuid not null references public.conversations(id) on delete cascade,
  sender_id uuid not null references auth.users(id) on delete cascade,
  body text not null check (char_length(body) between 1 and 2000),
  created_at timestamptz not null default now()
);

create index if not exists messages_conversation_created_idx
  on public.messages(conversation_id, created_at);

create index if not exists conversation_members_user_idx
  on public.conversation_members(user_id);

-- Create profile automatically after signup.
create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer set search_path = public
as $$
declare
  new_username text;
  new_display_name text;
begin
  new_username := lower(trim(coalesce(new.raw_user_meta_data->>'username', 'user_' || substr(new.id::text, 1, 8))));
  new_display_name := trim(coalesce(new.raw_user_meta_data->>'display_name', new_username));

  insert into public.profiles (id, username, display_name)
  values (new.id, new_username, new_display_name);

  return new;
exception
  when unique_violation then
    raise exception 'Username is already taken';
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
after insert on auth.users
for each row execute procedure public.handle_new_user();

-- Check username availability without exposing user emails.
create or replace function public.username_available(wanted_username text)
returns boolean
language sql
security definer set search_path = public
as $$
  select not exists (
    select 1 from public.profiles
    where lower(username) = lower(trim(wanted_username))
  );
$$;

grant execute on function public.username_available(text) to anon, authenticated;

-- Used by username login to turn a username into its auth email.
-- This intentionally returns only one email for a known username.
create or replace function public.email_for_username(wanted_username text)
returns text
language sql
security definer set search_path = public
as $$
  select u.email
  from public.profiles p
  join auth.users u on u.id = p.id
  where lower(p.username) = lower(trim(wanted_username))
  limit 1;
$$;

grant execute on function public.email_for_username(text) to anon, authenticated;

-- Create a 1-to-1 conversation if one does not already exist.
create or replace function public.create_direct_conversation(other_user_id uuid)
returns uuid
language plpgsql
security invoker
as $$
declare
  existing_id uuid;
  new_id uuid;
begin
  if other_user_id = auth.uid() then
    raise exception 'You cannot start a conversation with yourself';
  end if;

  if not exists (select 1 from public.profiles where id = other_user_id) then
    raise exception 'User not found';
  end if;

  select cm1.conversation_id into existing_id
  from public.conversation_members cm1
  join public.conversation_members cm2
    on cm2.conversation_id = cm1.conversation_id
  where cm1.user_id = auth.uid()
    and cm2.user_id = other_user_id
  limit 1;

  if existing_id is not null then
    return existing_id;
  end if;

  insert into public.conversations default values returning id into new_id;

  insert into public.conversation_members(conversation_id, user_id)
  values (new_id, auth.uid()), (new_id, other_user_id);

  return new_id;
end;
$$;

grant execute on function public.create_direct_conversation(uuid) to authenticated;

-- Enable RLS.
alter table public.profiles enable row level security;
alter table public.conversations enable row level security;
alter table public.conversation_members enable row level security;
alter table public.messages enable row level security;

-- Profiles: authenticated users can find users by username/display name.
drop policy if exists "profiles readable by authenticated users" on public.profiles;
create policy "profiles readable by authenticated users"
on public.profiles for select
to authenticated
using (true);

drop policy if exists "users can update own profile" on public.profiles;
create policy "users can update own profile"
on public.profiles for update
to authenticated
using (id = auth.uid())
with check (id = auth.uid());

-- Conversations: only members can read.
drop policy if exists "members can read conversations" on public.conversations;
create policy "members can read conversations"
on public.conversations for select
to authenticated
using (
  exists (
    select 1 from public.conversation_members cm
    where cm.conversation_id = conversations.id
      and cm.user_id = auth.uid()
  )
);

-- Membership: members can see membership rows for their conversations.
drop policy if exists "members can read memberships" on public.conversation_members;
create policy "members can read memberships"
on public.conversation_members for select
to authenticated
using (
  exists (
    select 1 from public.conversation_members mine
    where mine.conversation_id = conversation_members.conversation_id
      and mine.user_id = auth.uid()
  )
);

-- Messages: only conversation members can read.
drop policy if exists "members can read messages" on public.messages;
create policy "members can read messages"
on public.messages for select
to authenticated
using (
  exists (
    select 1 from public.conversation_members cm
    where cm.conversation_id = messages.conversation_id
      and cm.user_id = auth.uid()
  )
);

-- Messages: authenticated users can send only as themselves into a conversation they belong to.
drop policy if exists "members can send messages" on public.messages;
create policy "members can send messages"
on public.messages for insert
to authenticated
with check (
  sender_id = auth.uid()
  and exists (
    select 1 from public.conversation_members cm
    where cm.conversation_id = messages.conversation_id
      and cm.user_id = auth.uid()
  )
);

-- Enable Realtime for messages.
do $$
begin
  alter publication supabase_realtime add table public.messages;
exception
  when duplicate_object then null;
end $$;
